services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    # Ensure this port is not needed for bots but Render needs it to be specified
    port: 10000  # A dummy port number to satisfy Render's requirement
